server:
  servlet:
    context-path: /api/
spring:
  liquibase:
      change-log: classpath:/sql/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/familytree
    username: sasha
    password: sasha
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
      platform: postgres